project:
  type: website
  output-dir: _site

website:
  title: "Master Thesis Ecological Engineering"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: MCA_Belaege_Szenario_0_bis_3.qmd
        text: "MCA Szenarien - Beläge"
      - href: MCA_Baeume_Szenario_0_bis_3.qmd
        text: "MCA Szenarien - Bäume"
format:
  html:
    theme: darky
    toc: true
    code-fold: false
    code-tools: true

execute:
  freeze: auto
  warning: false
  message: false
